---
Name: MyAuth
After:
  - '#coresecurity'
---

#SilverStripe\Core\Injector\Injector:
#  SilverStripe\Security\Security:
#    properties:
#      Authenticators:
#        default: %$InsiteApps\Security\MemberAuthenticator\MembershipAuthenticator